#!/bin/bash

for SUBD in 24x24/*; do
    SUB=`basename ${SUBD}`
    for ICON in 24x24/$SUB/*.png; do
        NAME=`basename ${ICON} .png`
        for SIZE in 48 32 16 8; do
            mkdir -p ${SIZE}x${SIZE}/$SUB
            NEW=${SIZE}x${SIZE}/$SUB/${NAME}.png
            echo ${ICON} to ${NEW}
            convert ${ICON} -resize ${SIZE} ${NEW}
        done
    done
done
