Document: uecide
Title: Debian uecide Manual
Author: <insert document author here>
Abstract: This manual describes what uecide is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/uecide/uecide.sgml.gz

Format: postscript
Files: /usr/share/doc/uecide/uecide.ps.gz

Format: text
Files: /usr/share/doc/uecide/uecide.text.gz

Format: HTML
Index: /usr/share/doc/uecide/html/index.html
Files: /usr/share/doc/uecide/html/*.html
