#!/bin/bash

for SUBD in 48x48/*; do
    SUB=`basename ${SUBD}`
    for ICON in 48x48/$SUB/*.png; do
        NAME=`basename ${ICON} .png`
        for SIZE in 32 22 16 8; do
            NEW=${SIZE}x${SIZE}/$SUB/${NAME}.png
            echo ${ICON} to ${NEW}
            convert ${ICON} -resize ${SIZE} ${NEW}
        done
    done
done
