/* The following code was generated by JFlex 1.4.3 on 14/07/13 11:47 */

/*
 * 12/06/2004
 *
 * AssemblerAVRTokenMaker.java - An object that can take a chunk of text and
 * return a linked list of tokens representing AVR assembler.
 * 
 * This library is distributed under a modified BSD license.  See the included
 * RSyntaxTextArea.License.txt file for details.
 */
package org.fife.ui.rsyntaxtextarea.modes;

import java.io.*;
import javax.swing.text.Segment;

import org.fife.ui.rsyntaxtextarea.*;


/**
 * This class takes plain text and returns tokens representing x86
 * assembler.<p>
 *
 * This implementation was created using
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1; however, the generated file
 * was modified for performance.  Memory allocation needs to be almost
 * completely removed to be competitive with the handwritten lexers (subclasses
 * of <code>AbstractTokenMaker</code>, so this class has been modified so that
 * Strings are never allocated (via yytext()), and the scanner never has to
 * worry about refilling its buffer (needlessly copying chars around).
 * We can achieve this because RText always scans exactly 1 line of tokens at a
 * time, and hands the scanner this line as an array of characters (a Segment
 * really).  Since tokens contain pointers to char arrays instead of Strings
 * holding their contents, there is no need for allocating new memory for
 * Strings.<p>
 *
 * The actual algorithm generated for scanning has, of course, not been
 * modified.<p>
 *
 * If you wish to regenerate this file yourself, keep in mind the following:
 * <ul>
 *   <li>The generated AssemblerAVRTokenMaker.java</code> file will contain two
 *       definitions of both <code>zzRefill</code> and <code>yyreset</code>.
 *       You should hand-delete the second of each definition (the ones
 *       generated by the lexer), as these generated methods modify the input
 *       buffer, which we'll never have to do.</li>
 *   <li>You should also change the declaration/definition of zzBuffer to NOT
 *       be initialized.  This is a needless memory allocation for us since we
 *       will be pointing the array somewhere else anyway.</li>
 *   <li>You should NOT call <code>yylex()</code> on the generated scanner
 *       directly; rather, you should use <code>getTokenList</code> as you would
 *       with any other <code>TokenMaker</code> instance.</li>
 * </ul>
 *
 * @author Robert Futrell
 * @version 0.2
 *
 */

public class AssemblerAVRTokenMaker extends AbstractJFlexTokenMaker {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\10\1\7\1\0\1\10\23\0\1\10\1\14\1\4\2\0"+
    "\1\13\1\14\1\5\2\0\1\12\1\12\1\3\1\12\1\15\1\12"+
    "\1\46\1\45\1\47\1\50\1\44\1\2\1\2\1\2\1\44\1\2"+
    "\1\11\1\6\1\14\1\14\1\14\2\0\1\34\1\16\1\22\1\25"+
    "\1\21\1\26\1\24\1\52\1\30\1\51\1\1\1\42\1\33\1\32"+
    "\1\36\1\43\1\37\1\35\1\23\1\20\1\40\1\27\1\31\1\41"+
    "\1\17\1\53\1\3\1\0\1\3\1\14\1\1\1\0\1\34\1\16"+
    "\1\22\1\25\1\21\1\26\1\24\1\52\1\30\1\51\1\1\1\42"+
    "\1\33\1\32\1\36\1\43\1\37\1\35\1\23\1\20\1\40\1\27"+
    "\1\31\1\41\1\17\1\53\1\0\1\14\1\0\1\14\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\2\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\22\1\1\11\1\1\1\12\1\13\1\14\12\0"+
    "\21\1\1\15\1\1\1\15\3\1\1\11\1\1\1\11"+
    "\2\1\1\15\7\1\1\16\2\1\2\16\2\15\1\1"+
    "\6\0\1\12\6\0\1\1\1\15\12\1\2\15\5\1"+
    "\7\0\1\17\3\1\4\0\1\12\2\1\3\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\130\0\u0160\0\130\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c"+
    "\0\u0268\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c"+
    "\0\u03c8\0\u03f4\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04d0\0\u04d0"+
    "\0\130\0\130\0\u04fc\0\u0528\0\u0554\0\u0580\0\u05ac\0\u05d8"+
    "\0\u0604\0\u0630\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738"+
    "\0\u0764\0\u0790\0\u07bc\0\u07e8\0\u0814\0\u0840\0\u086c\0\u0898"+
    "\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0974\0\u09a0\0\u09cc\0\u09f8"+
    "\0\u0a24\0\u0a50\0\u0a7c\0\204\0\u0aa8\0\u086c\0\u0ad4\0\u0b00"+
    "\0\u0aa8\0\u0b2c\0\u0b58\0\u0b84\0\u0bb0\0\u0bdc\0\u0c08\0\u0c34"+
    "\0\204\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4\0\u0d10\0\u0d3c\0\u0d68"+
    "\0\u0d94\0\u0dc0\0\u0dec\0\u0e18\0\u0e44\0\u0e70\0\130\0\u0e9c"+
    "\0\u0ec8\0\u0ef4\0\u0f20\0\u0f4c\0\u0f78\0\u0fa4\0\204\0\u0fd0"+
    "\0\u0ffc\0\u1028\0\u1054\0\u1080\0\u10ac\0\u0d10\0\u10d8\0\u1104"+
    "\0\u1130\0\u115c\0\u0fd0\0\u1188\0\u11b4\0\u11e0\0\u120c\0\u1238"+
    "\0\u1264\0\u1290\0\u12bc\0\u12e8\0\u1314\0\u1340\0\u136c\0\204"+
    "\0\u1398\0\u13c4\0\u13f0\0\u141c\0\u1448\0\u1474\0\u14a0\0\u14cc"+
    "\0\u14f8\0\u1524\0\u1550\0\u157c\0\u15a8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\6\1\7\1\10\1\11"+
    "\1\12\1\3\3\13\1\14\1\15\1\4\1\16\1\17"+
    "\1\20\1\21\1\4\1\22\1\23\1\4\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\23\2\4\1\33"+
    "\1\34\5\5\1\35\2\4\1\3\1\4\1\5\1\3"+
    "\1\6\1\7\1\10\1\11\1\12\1\3\1\13\1\36"+
    "\1\13\1\14\1\15\1\4\1\16\1\17\1\20\1\21"+
    "\1\4\1\22\1\23\1\4\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\23\2\4\1\33\1\34\5\5"+
    "\1\35\2\4\54\0\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\36\4\1\37\1\4\1\5"+
    "\1\0\3\37\2\0\1\40\2\0\1\37\1\0\26\4"+
    "\5\5\3\4\4\6\1\41\47\6\5\7\1\42\46\7"+
    "\7\10\1\0\44\10\10\0\1\12\61\0\1\43\2\0"+
    "\1\44\1\45\1\46\1\0\1\47\2\0\1\50\1\0"+
    "\1\51\1\52\2\0\1\53\3\0\1\54\11\0\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\1\4\1\55\1\56\1\4\1\57\1\60\11\4\1\61"+
    "\4\4\1\62\11\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\1\63\2\4\1\64\1\4"+
    "\1\65\4\4\1\66\1\67\22\4\1\37\2\4\1\0"+
    "\3\37\2\0\1\40\2\0\1\37\1\0\20\4\1\70"+
    "\1\71\14\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\1\72\15\4\1\73\1\4\1\74"+
    "\3\4\1\75\1\76\10\4\1\37\2\4\1\0\3\37"+
    "\2\0\1\40\2\0\1\37\1\0\1\77\1\4\1\100"+
    "\1\75\3\4\1\23\3\4\1\101\6\4\1\102\1\4"+
    "\1\103\11\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\1\104\1\4\1\104\1\105\3\4"+
    "\2\104\2\4\1\106\5\4\1\104\1\107\13\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\13\4\1\67\22\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\4\4\1\110\7\4\1\111"+
    "\16\4\1\35\2\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\7\4\1\70\10\4\1\112"+
    "\15\4\1\37\2\4\1\0\3\37\2\0\1\40\2\0"+
    "\1\37\1\0\3\4\1\113\14\4\1\114\15\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\20\4\1\115\1\4\1\116\13\4\1\37\2\4\1\0"+
    "\3\37\2\0\1\40\2\0\1\37\1\0\5\4\1\70"+
    "\1\4\1\117\4\4\1\120\21\4\1\37\1\4\1\121"+
    "\1\0\3\37\2\0\1\40\2\0\1\37\1\0\3\4"+
    "\1\122\1\110\13\4\1\123\5\4\1\121\1\124\1\121"+
    "\1\124\1\125\1\35\2\4\1\37\2\4\1\0\3\37"+
    "\2\0\1\40\2\0\1\37\1\0\17\4\1\126\2\4"+
    "\1\65\13\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\5\4\1\123\1\4\1\127\15\4"+
    "\1\74\10\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\20\4\1\114\1\4\1\130\13\4"+
    "\1\37\2\4\1\0\3\37\2\0\1\40\2\0\1\37"+
    "\1\0\15\4\1\114\20\4\1\0\2\36\13\0\36\36"+
    "\3\37\1\0\3\37\2\0\1\37\2\0\1\37\1\0"+
    "\36\37\17\0\1\131\57\0\1\132\6\0\1\133\4\0"+
    "\1\134\1\0\1\135\35\0\1\132\51\0\1\136\50\0"+
    "\1\137\2\0\1\140\1\0\1\132\5\0\1\137\54\0"+
    "\1\141\57\0\1\142\51\0\1\143\54\0\1\144\46\0"+
    "\1\145\23\0\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\2\4\1\146\33\4\1\37\2\4"+
    "\1\0\3\37\2\0\1\40\2\0\1\37\1\0\17\4"+
    "\1\105\16\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\24\4\1\70\11\4\1\37\2\4"+
    "\1\0\3\37\2\0\1\40\2\0\1\37\1\0\2\4"+
    "\1\147\1\65\32\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\1\150\1\4\1\151\1\152"+
    "\1\150\1\153\1\154\2\4\1\150\1\155\1\4\1\154"+
    "\1\156\6\4\1\157\1\116\6\4\1\150\1\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\7\4\1\147\26\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\1\4\1\55\34\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\23\4\1\160\12\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\2\4\1\147\33\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\15\4\1\161\20\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\20\4\1\112\15\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\17\4\1\147\16\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\22\4\1\104\13\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\12\4\1\147\4\4\1\147\16\4\1\37\2\4\1\0"+
    "\3\37\2\0\1\40\2\0\1\37\1\0\24\4\1\116"+
    "\11\4\1\37\2\4\1\0\3\37\2\0\1\40\2\0"+
    "\1\37\1\0\15\4\1\147\20\4\1\37\2\4\1\0"+
    "\3\37\2\0\1\40\2\0\1\37\1\0\2\4\1\147"+
    "\1\4\2\147\3\4\2\147\1\4\1\147\2\4\1\147"+
    "\14\4\2\147\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\4\4\1\147\1\154\4\4\1\147"+
    "\23\4\1\37\2\4\1\0\3\37\2\0\1\40\2\0"+
    "\1\37\1\0\1\4\1\55\2\4\1\126\5\4\1\162"+
    "\4\4\1\163\16\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\5\4\1\147\1\4\1\147"+
    "\26\4\1\37\2\4\1\0\3\37\2\0\1\40\2\0"+
    "\1\37\1\0\16\4\1\114\1\4\1\112\15\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\1\126\35\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\3\4\1\164\32\4\1\37\2\4"+
    "\1\0\3\37\2\0\1\40\2\0\1\37\1\0\4\4"+
    "\1\147\31\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\25\4\1\104\10\4\1\37\2\4"+
    "\1\0\3\37\2\0\1\40\2\0\1\37\1\0\16\4"+
    "\1\73\17\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\17\4\1\165\16\4\1\37\2\4"+
    "\1\0\3\37\2\0\1\40\2\0\1\37\1\0\6\4"+
    "\1\147\27\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\25\4\1\147\10\4\1\37\2\4"+
    "\1\0\3\37\2\0\1\40\2\0\1\37\1\0\11\4"+
    "\1\147\24\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\24\4\1\147\11\4\1\37\2\4"+
    "\1\0\3\37\2\0\1\40\2\0\1\37\1\0\4\4"+
    "\1\147\2\4\1\147\2\4\1\166\23\4\1\37\2\4"+
    "\1\0\3\37\2\0\1\40\2\0\1\37\1\0\7\4"+
    "\1\126\26\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\2\4\1\126\2\4\1\167\10\4"+
    "\1\170\17\4\1\37\2\4\1\0\3\37\2\0\1\40"+
    "\2\0\1\37\1\0\17\4\1\147\4\4\1\147\11\4"+
    "\1\37\1\4\1\121\1\0\3\37\2\0\1\40\2\0"+
    "\1\37\1\0\26\4\5\121\3\4\1\37\2\4\1\0"+
    "\3\37\2\0\1\40\2\0\1\37\1\0\27\4\2\121"+
    "\5\4\1\37\2\4\1\0\3\37\2\0\1\40\2\0"+
    "\1\37\1\0\12\4\1\147\23\4\1\37\2\4\1\0"+
    "\3\37\2\0\1\40\2\0\1\37\1\0\5\4\1\147"+
    "\1\4\1\147\2\4\1\147\23\4\1\37\2\4\1\0"+
    "\3\37\2\0\1\40\2\0\1\37\1\0\5\4\1\153"+
    "\30\4\20\0\1\171\54\0\1\144\57\0\1\172\66\0"+
    "\1\137\43\0\1\136\43\0\1\137\61\0\1\137\1\173"+
    "\46\0\1\174\73\0\1\175\33\0\1\176\55\0\1\137"+
    "\52\0\1\177\30\0\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\3\4\1\200\32\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\4\4\2\147\30\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\5\4\1\147\30\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\21\4\1\147\14\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\34\4\1\147\1\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\3\4\1\147\32\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\3\4\1\147\3\4\1\147"+
    "\26\4\1\37\2\4\1\0\3\37\2\0\1\40\2\0"+
    "\1\37\1\0\2\4\1\147\15\4\1\147\15\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\2\4\1\201\33\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\3\4\1\202\32\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\4\4\2\147\5\4\1\147\22\4\1\37\2\4\1\0"+
    "\3\37\2\0\1\40\2\0\1\37\1\0\3\4\1\114"+
    "\32\4\1\37\2\4\1\0\3\37\2\0\1\40\2\0"+
    "\1\37\1\0\7\4\1\200\26\4\1\37\2\4\1\0"+
    "\3\37\2\0\1\40\2\0\1\37\1\0\13\4\1\147"+
    "\22\4\1\37\2\4\1\0\3\37\2\0\1\40\2\0"+
    "\1\37\1\0\1\104\1\4\1\104\4\4\1\104\3\4"+
    "\1\104\5\4\1\104\14\4\1\37\2\4\1\0\3\37"+
    "\2\0\1\40\2\0\1\37\1\0\24\4\1\203\11\4"+
    "\21\0\1\137\65\0\1\52\50\0\1\204\65\0\1\205"+
    "\41\0\1\206\60\0\1\207\36\0\1\210\33\0\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\3\4\1\211\32\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\5\4\1\104\30\4\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\26\4\1\200\1\212\6\4\22\0\1\171\71\0\1\213"+
    "\36\0\1\136\66\0\1\137\50\0\1\214\20\0\1\37"+
    "\2\4\1\0\3\37\2\0\1\40\2\0\1\37\1\0"+
    "\21\4\1\71\14\4\1\37\2\4\1\0\3\37\2\0"+
    "\1\40\2\0\1\37\1\0\30\4\1\200\5\4\25\0"+
    "\1\171\62\0\1\215\41\0\1\137\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5588];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\5\1\1\11\1\1\1\11\25\1\2\11"+
    "\12\0\54\1\6\0\1\11\6\0\23\1\7\0\4\1"+
    "\4\0\3\1\3\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[141];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */


	/**
	 * Constructor.  We must have this here as JFLex does not generate a
	 * no parameter constructor.
	 */
	public AssemblerAVRTokenMaker() {
		super();
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int tokenType) {
		addToken(zzStartRead, zzMarkedPos-1, tokenType);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param tokenType The token's type.
	 */
	private void addToken(int start, int end, int tokenType) {
		int so = start + offsetShift;
		addToken(zzBuffer, start,end, tokenType, so);
	}


	/**
	 * Adds the token specified to the current linked list of tokens.
	 *
	 * @param array The character array.
	 * @param start The starting offset in the array.
	 * @param end The ending offset in the array.
	 * @param tokenType The token's type.
	 * @param startOffset The offset in the document at which this token
	 *                    occurs.
	 */
	public void addToken(char[] array, int start, int end, int tokenType, int startOffset) {
		super.addToken(array, start,end, tokenType, startOffset);
		zzStartRead = zzMarkedPos;
	}


	/**
	 * Returns the text to place at the beginning and end of a
	 * line to "comment" it in a this programming language.
	 *
	 * @return The start and end strings to add to a line to "comment"
	 *         it out.
	 */
	public String[] getLineCommentStartAndEnd() {
		return new String[] { ";", null };
	}


	/**
	 * Returns the first token in the linked list of tokens generated
	 * from <code>text</code>.  This method must be implemented by
	 * subclasses so they can correctly implement syntax highlighting.
	 *
	 * @param text The text from which to get tokens.
	 * @param initialTokenType The token type we should start with.
	 * @param startOffset The offset into the document at which
	 *                    <code>text</code> starts.
	 * @return The first <code>Token</code> in a linked list representing
	 *         the syntax highlighted text.
	 */
	public Token getTokenList(Segment text, int initialTokenType, int startOffset) {

		resetTokenList();
		this.offsetShift = -text.offset + startOffset;

		// Start off in the proper state.
		int state = Token.NULL;
		switch (initialTokenType) {
			default:
				state = Token.NULL;
		}

		s = text;
		try {
			yyreset(zzReader);
			yybegin(state);
			return yylex();
		} catch (IOException ioe) {
			ioe.printStackTrace();
			return new Token();
		}

	}


	/**
	 * Refills the input buffer.
	 *
	 * @return      <code>true</code> if EOF was reached, otherwise
	 *              <code>false</code>.
	 * @exception   IOException  if any I/O-Error occurs.
	 */
	private boolean zzRefill() throws java.io.IOException {
		return zzCurrentPos>=s.offset+s.count;
	}


	/**
	 * Resets the scanner to read from a new input stream.
	 * Does not close the old reader.
	 *
	 * All internal variables are reset, the old input stream 
	 * <b>cannot</b> be reused (internal buffer is discarded and lost).
	 * Lexical state is set to <tt>YY_INITIAL</tt>.
	 *
	 * @param reader   the new input stream 
	 */
	public final void yyreset(java.io.Reader reader) throws java.io.IOException {
		// 's' has been updated.
		zzBuffer = s.array;
		/*
		 * We replaced the line below with the two below it because zzRefill
		 * no longer "refills" the buffer (since the way we do it, it's always
		 * "full" the first time through, since it points to the segment's
		 * array).  So, we assign zzEndRead here.
		 */
		//zzStartRead = zzEndRead = s.offset;
		zzStartRead = s.offset;
		zzEndRead = zzStartRead + s.count - 1;
		zzCurrentPos = zzMarkedPos = s.offset;
		zzLexicalState = YYINITIAL;
		zzReader = reader;
		zzAtBOL  = true;
		zzAtEOF  = false;
	}




  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AssemblerAVRTokenMaker(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public AssemblerAVRTokenMaker(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public org.fife.ui.rsyntaxtextarea.Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 13: 
          { addToken(Token.RESERVED_WORD);
          }
        case 16: break;
        case 1: 
          { addToken(Token.IDENTIFIER);
          }
        case 17: break;
        case 11: 
          { addToken(Token.LITERAL_STRING_DOUBLE_QUOTE);
          }
        case 18: break;
        case 9: 
          { addToken(Token.FUNCTION);
          }
        case 19: break;
        case 5: 
          { addToken(Token.COMMENT_EOL); addNullToken(); return firstToken;
          }
        case 20: break;
        case 14: 
          { addToken(Token.VARIABLE);
          }
        case 21: break;
        case 7: 
          { addToken(Token.WHITESPACE);
          }
        case 22: break;
        case 10: 
          { addToken(Token.PREPROCESSOR);
          }
        case 23: break;
        case 15: 
          { addToken(Token.DATA_TYPE);
          }
        case 24: break;
        case 4: 
          { addToken(Token.ERROR_CHAR); /*addNullToken(); return firstToken;*/
          }
        case 25: break;
        case 8: 
          { addToken(Token.OPERATOR);
          }
        case 26: break;
        case 2: 
          { addToken(Token.LITERAL_NUMBER_DECIMAL_INT);
          }
        case 27: break;
        case 12: 
          { addToken(Token.LITERAL_CHAR);
          }
        case 28: break;
        case 3: 
          { addToken(Token.ERROR_STRING_DOUBLE); addNullToken(); return firstToken;
          }
        case 29: break;
        case 6: 
          { addNullToken(); return firstToken;
          }
        case 30: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case YYINITIAL: {
              addNullToken(); return firstToken;
            }
            case 142: break;
            default:
            return null;
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
